name: 'Secure Webhook'
description: 'Send a SHA256 digest with webhook request'
branding:
  icon: 'alert-octagon'
  color: 'green'
inputs:
  url:
    description: 'Request URL'
    required: true
  hmacSecret:
    description: 'HMAC Secret'
    required: true
  data:
    description: 'Request Body'
    required: false
  headers:
    description: 'Additional headers as JSON object'
    required: false
  timeout:
    description: 'Request timeout in milliseconds'
    required: false
    default: '30000'
  retries:
    description: 'Number of retry attempts'
    required: false
    default: '3'
outputs:
  response:
    description: 'HTTP Response (JSON with status and data)'
runs:
  using: 'node20'
  main: 'dist/index.js'